name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'
    
    - name: Set up environment
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: |
        echo "$env:GOOGLE_CREDENTIALS_JSON" | Set-Content .env
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6==6.4.2
        pip install PyQt6-sip==13.5.0
        pip install pandas==1.5.3
        pip install numpy==1.24.3
        pip install google-auth==2.22.0
        pip install google-auth-oauthlib==1.0.0
        pip install google-auth-httplib2==0.1.0
        pip install google-api-python-client==2.93.0
        pip install python-dotenv==1.0.0
        pip install pyinstaller==6.1.0
        
    - name: Build executable
      run: |
        & pyinstaller --clean --onefile --noconsole --icon=app_icon.ico --name LogProcessor `
        --hidden-import=PyQt6.sip your_main_app.py
        
    - name: Create ZIP with required files
      run: |
        cd dist
        Copy-Item ../.env .
        Compress-Archive -Path LogProcessor.exe,.env -DestinationPath LogProcessor_Windows.zip
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LogProcessor_Windows
        path: dist/LogProcessor_Windows.zip
